name: Deploy ICC Dashboard

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Runs for every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/icc-dashboard:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push shalinikallepalli21/icc-dashboard:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yml
          kubectl rollout restart deployment icc-dashboard
